################################################################################
##                            Junkdarc 1.0                                    ##
################################################################################
##                                                                            ##
##      Hergestellt für den Citybuild Server Mining-Royal                     ##
##                                                                            ##
##                    Author : Junkdarc                                       ##
##                    Website: www.Mining-Royal.de                            ##
##                    Teamspeak: Mining-Royal.de                              ##
##                                                                            ##
################################################################################
################################################################################
##                                                                            ##
##                                SOCIALS                                     ##
##                                                                            ##
################################################################################
##      teamspeakip gibt die nachfolgende Teamspeak IP wieder                 ##
##                Für die Befehle /ts, ts3, teamspeak                         ##
################################################################################
teamspeakip : 'Mining-Royal.de'
################################################################################
##              forum gibt die nachfolgende Forum URL wieder                  ##
##                für die Befehle /hp, forum, homepage                        ##
################################################################################
forum: 'Mining-Royal.de'